import Foundation

/// Pre-bundled cache of the most popular Bible verses for ESV (and future NLT).
/// Loaded from JSON files in the app bundle at startup. Provides instant offline
/// access to common verses without API calls.
///
/// The cache files are generated by `fetch_popular_verses.py` which fetches
/// from the translation APIs and saves structured JSON.
public final class PopularVerseCache: @unchecked Sendable {

    public static let shared = PopularVerseCache()

    // MARK: - Types

    private struct CachedPassage: Codable {
        let reference: String     // e.g. "John 3:16" or "Psalm 23:1-6"
        let text: String          // Full passage text with verse numbers
        let canonical: String     // Canonical reference from API
    }

    // MARK: - Storage

    /// Keyed by lowercase canonical reference → passage text
    private var esvCache: [String: CachedPassage] = [:]
    private var nltCache: [String: CachedPassage] = [:]
    private var isLoaded = false
    private let lock = NSLock()

    // MARK: - Loading

    /// Load bundled cache files. Call once at app startup.
    public func loadIfNeeded() {
        lock.lock()
        defer { lock.unlock() }
        guard !isLoaded else { return }
        isLoaded = true

        esvCache = loadCache(filename: "esv_popular_cache")
        nltCache = loadCache(filename: "nlt_popular_cache")
    }

    private func loadCache(filename: String) -> [String: CachedPassage] {
        guard let url = Bundle.main.url(forResource: filename, withExtension: "json"),
              let data = try? Data(contentsOf: url),
              let passages = try? JSONDecoder().decode([CachedPassage].self, from: data)
        else { return [:] }

        var dict: [String: CachedPassage] = [:]
        for passage in passages {
            let key = passage.reference.lowercased()
            dict[key] = passage
            // Also index by canonical form
            let canonicalKey = passage.canonical.lowercased()
            if canonicalKey != key {
                dict[canonicalKey] = passage
            }
        }
        return dict
    }

    // MARK: - Lookup

    /// Look up a popular verse by reference string. Returns the passage text if cached.
    public func lookup(reference: String, translation: Translation) -> String? {
        loadIfNeeded()
        let key = reference.lowercased()
        switch translation {
        case .esv: return esvCache[key]?.text
        case .nlt: return nltCache[key]?.text
        case .kjv: return nil  // KJV is always local SQLite
        }
    }

    /// Check if a reference is in the popular cache.
    public func contains(reference: String, translation: Translation) -> Bool {
        loadIfNeeded()
        let key = reference.lowercased()
        switch translation {
        case .esv: return esvCache[key] != nil
        case .nlt: return nltCache[key] != nil
        case .kjv: return false
        }
    }

    /// Parse cached passage text into individual Verse objects.
    /// Handles the ESV API format: "[1] verse text [2] verse text..."
    public func verses(book: String, chapter: Int, verse: Int, endVerse: Int? = nil, translation: Translation) -> [Verse]? {
        let ref: String
        if let end = endVerse {
            ref = "\(book) \(chapter):\(verse)-\(end)"
        } else {
            ref = "\(book) \(chapter):\(verse)"
        }

        guard let text = lookup(reference: ref, translation: translation) else {
            return nil
        }

        // Parse verse-numbered text into individual Verse objects
        return parseNumberedText(text, book: book, chapter: chapter, startVerse: verse, translation: translation)
    }

    // MARK: - Parsing

    /// Parse "[1] text [2] text..." format into Verse array.
    private func parseNumberedText(_ text: String, book: String, chapter: Int, startVerse: Int, translation: Translation) -> [Verse] {
        // Pattern: [N] followed by text until next [N] or end
        let pattern = #"\[(\d+)\]\s*"#
        guard let regex = try? NSRegularExpression(pattern: pattern) else {
            // No verse numbers found — return as single verse
            return [Verse(
                id: syntheticId(translation: translation, chapter: chapter, verse: startVerse),
                bookName: book,
                chapterNumber: chapter,
                verseNumber: startVerse,
                text: text.trimmingCharacters(in: .whitespacesAndNewlines),
                translation: translation.rawValue
            )]
        }

        let nsText = text as NSString
        let matches = regex.matches(in: text, range: NSRange(location: 0, length: nsText.length))

        if matches.isEmpty {
            return [Verse(
                id: syntheticId(translation: translation, chapter: chapter, verse: startVerse),
                bookName: book,
                chapterNumber: chapter,
                verseNumber: startVerse,
                text: text.trimmingCharacters(in: .whitespacesAndNewlines),
                translation: translation.rawValue
            )]
        }

        var verses: [Verse] = []
        for (i, match) in matches.enumerated() {
            let verseNum = Int(nsText.substring(with: match.range(at: 1))) ?? startVerse
            let textStart = match.range.location + match.range.length
            let textEnd: Int
            if i + 1 < matches.count {
                textEnd = matches[i + 1].range.location
            } else {
                textEnd = nsText.length
            }

            let verseText = nsText.substring(with: NSRange(location: textStart, length: textEnd - textStart))
                .trimmingCharacters(in: .whitespacesAndNewlines)

            guard !verseText.isEmpty else { continue }

            verses.append(Verse(
                id: syntheticId(translation: translation, chapter: chapter, verse: verseNum),
                bookName: book,
                chapterNumber: chapter,
                verseNumber: verseNum,
                text: verseText,
                translation: translation.rawValue
            ))
        }

        return verses
    }

    private func syntheticId(translation: Translation, chapter: Int, verse: Int) -> Int {
        let offset: Int
        switch translation {
        case .kjv: offset = 0
        case .esv: offset = 1_000_000
        case .nlt: offset = 2_000_000
        }
        return offset + chapter * 1000 + verse
    }
}
